### ISSUE TITLE
ImportError: No module named backports.ssl_match_hostname

### ISSUE THREAD

**Issue by xuhang57** [cyverse/clank#157]
```cmd: ./manage.py migrate --noinput --settings=troposphere.settings --pythonpath=/opt/dev/troposphere

msg:
:stderr: Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/env/troposphere/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/opt/env/troposphere/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/env/troposphere/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/env/troposphere/local/lib/python2.7/site-packages/django/core/management/base.py", line 398, in execute
    self.check()
  File "/opt/env/troposphere/local/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/env/troposphere/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/env/troposphere/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/opt/env/troposphere/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "/opt/env/troposphere/local/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/env/troposphere/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/env/troposphere/local/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/env/troposphere/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/dev/troposphere/troposphere/urls.py", line 6, in <module>
    from troposphere import views
  File "/opt/dev/troposphere/troposphere/views/__init__.py", line 5, in <module>
    from .auth import login, logout, cas_oauth_service
  File "/opt/dev/troposphere/troposphere/views/auth.py", line 18, in <module>
    from django_cyverse_auth.authBackends import get_or_create_user, create_user_and_token
  File "/opt/env/troposphere/local/lib/python2.7/site-packages/django_cyverse_auth/authBackends.py", line 10, in <module>
    from libcloud.common.openstack_identity import OpenStackIdentity_3_0_Connection, OpenStackIdentityTokenScope
  File "/opt/env/troposphere/local/lib/python2.7/site-packages/libcloud/common/openstack_identity.py", line 24, in <module>
    from libcloud.utils.py3 import httplib
  File "/opt/env/troposphere/local/lib/python2.7/site-packages/libcloud/utils/py3.py", line 65, in <module>
    from backports.ssl_match_hostname import match_hostname, CertificateError  # NOQA
ImportError: No module named backports.ssl_match_hostname


NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=125  changed=30   unreach
```
I did: 

```pip install backports.ssl_match_hostname```

Testing it. More details soon

**Comment by xuhang57** [comment]
This  happened in the virtual env `troposphere`. I uninstalled it and the re-installation fixed the problem.
