### ISSUE TITLE
Cannot restart atmosphere on Ubuntu 16.04

### ISSUE THREAD

**Issue by xuhang57** [cyverse/clank#184]
Successfully deploy atmosphere/troposphere with clank on a Ubuntu16.04 VM. But run into a problem that I cannot run

`service atmosphere restart` and error log is: 

```(atmo) root@test-server:/opt/dev/atmosphere# service atmosphere start
(atmo) root@test-server:/opt/dev/atmosphere# journalctl -xe
Jun 14 18:25:38 test-server sh[12019]:   File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/platforms.py", line 151, in acq
Jun 14 18:25:38 test-server sh[12019]:     reraise(LockFailed, LockFailed(str(exc)), sys.exc_info()[2])
Jun 14 18:25:38 test-server sh[12019]:   File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/platforms.py", line 149, in acq
Jun 14 18:25:38 test-server sh[12019]:     self.write_pid()
Jun 14 18:25:38 test-server sh[12019]:   File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/platforms.py", line 212, in wri
Jun 14 18:25:38 test-server sh[12019]:     pidfile_fd = os.open(self.path, PIDFILE_FLAGS, PIDFILE_MODE)
Jun 14 18:25:38 test-server sh[12019]: celery.platforms.LockFailed: [Errno 2] No such file or directory: '/var/run/celery/atmosphere-
Jun 14 18:25:39 test-server sh[12019]: celery multi v4.0.2 (latentcall)
Jun 14 18:25:39 test-server sh[12019]: > Starting nodes...
Jun 14 18:25:39 test-server sh[12019]:         > $CELERYD_NODES@test-server: OK
Jun 14 18:25:39 test-server sh[12019]:         > atmosphere-deploy_1@test-server: OK
Jun 14 18:25:39 test-server sh[12019]:         > atmosphere-deploy_1@test-server: OK
Jun 14 18:25:39 test-server sh[12019]:         > $CELERYD_OPTS@test-server: OK
Jun 14 18:25:39 test-server sh[12019]: Traceback (most recent call last):
Jun 14 18:25:39 test-server sh[12019]:   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
Jun 14 18:25:39 test-server sh[12019]:     "__main__", fname, loader, pkg_name)
Jun 14 18:25:39 test-server sh[12019]:   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
Jun 14 18:25:39 test-server sh[12019]:     exec code in run_globals
Jun 14 18:25:39 test-server sh[12019]:   File "/opt/env/atmo/lib/python2.7/site-packages/celery/__main__.py", line 18, in <module>
Jun 14 18:25:39 test-server sh[12019]:     main()
Jun 14 18:25:39 test-server sh[12019]:   File "/opt/env/atmo/lib/python2.7/site-packages/celery/__main__.py", line 14, in main
Jun 14 18:25:39 test-server sh[12019]:     _main()
Jun 14 18:25:39 test-server sh[12019]:   File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/bin/celery.py", line 326, in ma
Jun 14 18:25:39 test-server sh[12019]:     cmd.execute_from_commandline(argv)
Jun 14 18:25:39 test-server sh[12019]:   File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/bin/celery.py", line 488, in ex
Jun 14 18:25:39 test-server sh[12019]:     super(CeleryCommand, self).execute_from_commandline(argv)))
Jun 14 18:25:39 test-server sh[12019]:   File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/bin/base.py", line 281, in exec
Jun 14 18:25:39 test-server sh[12019]:     return self.handle_argv(self.prog_name, argv[1:])
Jun 14 18:25:39 test-server sh[12019]:   File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/bin/celery.py", line 480, in ha
Jun 14 18:25:39 test-server sh[12019]:     return self.execute(command, argv)
Jun 14 18:25:39 test-server sh[12019]:   File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/bin/celery.py", line 412, in ex
Jun 14 18:25:39 test-server sh[12019]:     ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
Jun 14 18:25:39 test-server sh[12019]:   File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/bin/worker.py", line 220, in ru
Jun 14 18:25:39 test-server sh[12019]:     self.maybe_detach([command] + argv)
Jun 14 18:25:39 test-server sh[12019]:   File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/bin/worker.py", line 227, in ma
Jun 14 18:25:39 test-server sh[12019]:     detached_celeryd(self.app).execute_from_commandline(argv)
Jun 14 18:25:39 test-server sh[12019]:   File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/bin/celeryd_detach.py", line 96
Jun 14 18:25:39 test-server sh[12019]:     **vars(options)
Jun 14 18:25:39 test-server sh[12019]:   File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/bin/celeryd_detach.py", line 32
Jun 14 18:25:39 test-server sh[12019]:     after_forkers=False):
Jun 14 18:25:39 test-server sh[12019]:   File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/platforms.py", line 334, in ope
Jun 14 18:25:39 test-server sh[12019]:     self.after_chdir()
Jun 14 18:25:39 test-server sh[12019]:   File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/platforms.py", line 414, in aft
Jun 14 18:25:39 test-server sh[12019]:     _create_pidlock(pidfile).release()
Jun 14 18:25:39 test-server sh[12019]:   File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/platforms.py", line 262, in _cr
Jun 14 18:25:39 test-server sh[12019]:     pidlock.acquire()
Jun 14 18:25:39 test-server sh[12019]:   File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/platforms.py", line 151, in acq
Jun 14 18:25:39 test-server sh[12019]:     reraise(LockFailed, LockFailed(str(exc)), sys.exc_info()[2])
Jun 14 18:25:39 test-server sh[12019]:   File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/platforms.py", line 149, in acq
Jun 14 18:25:39 test-server sh[12019]:     self.write_pid()
Jun 14 18:25:39 test-server sh[12019]:   File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/platforms.py", line 212, in wri
Jun 14 18:25:39 test-server sh[12019]:     pidfile_fd = os.open(self.path, PIDFILE_FLAGS, PIDFILE_MODE)
Jun 14 18:25:39 test-server sh[12019]: celery.platforms.LockFailed: [Errno 2] No such file or directory: '/var/run/celery/$CELERYD_OP 
```

**Comment by steve-gregory** [comment]
@xuhang57 Are you using the `systemd` extras?

@calvinmclean is working on a more robust solution that will include a README on how to initiate commands for Ubuntu 16.04

**Comment by xuhang57** [comment]
@steve-gregory oops, didn't know about the `systemd` extras. It would be great if we could have some docs on how to use it 👍  Thanks!
